name: Test JmesPath Rules

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-jmespath:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t jmespath-tester .

      # Step 4: Run the Docker container with the jmespath files mounted
      - name: Run tests in Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/data jmespath-tester
          
      # Step 5: Check exit code
      - name: Ensure exit code is 0
        run: exit $?
